version: '3.8'

services:
  backend:
    build: .
    container_name: educenter-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped