// Generates src/services/email-templates-embedded.ts so email templates are
// bundled inside the serverless function (Vercel includeFiles is unreliable
// with the legacy builds format). Re-run after editing any .ejs template:
//   npx tsx src/scripts/generateEmbeddedEmailTemplates.ts
import fs from "fs";
import path from "path";

const dir = path.join(__dirname, "..", "services", "email-templates");
const headerPath = path.join(dir, "partials", "header.ejs");
const footerPath = path.join(dir, "partials", "footer.ejs");
const outPath = path.join(__dirname, "..", "services", "email-templates-embedded.ts");

const headerRaw = fs.readFileSync(headerPath, "utf-8");
const footerRaw = fs.readFileSync(footerPath, "utf-8");

// Header partial references icon/title/subtitle/headerColor/headerColorEnd.
// Rename them to __h.* so they stay scoped when inlined into the template.
const headerInlined = headerRaw.replace(
  /\b(icon|title|subtitle|headerColor|headerColorEnd)\b/g,
  "__h.$1"
);

const inline = (template: string): string => {
  let out = template;
  // <%- include('partials/header', { key: "value", ... }) %>
  out = out.replace(
    /<%- include\(['"]partials\/header['"],\s*\{([\s\S]*?)\}\)\s*%>/g,
    (_m, optionsBody: string) => {
      const pairs: string[] = [];
      const pairRe = /(\w+):\s*("[^"]*"|'[^']*'|[0-9a-fA-F#]+)/g;
      let match: RegExpExecArray | null;
      while ((match = pairRe.exec(optionsBody)) !== null) {
        pairs.push(`${match[1]}: ${match[2]}`);
      }
      return `<% const __h = { ${pairs.join(", ")} }; %>\n${headerInlined}`;
    }
  );
  // <%- include('partials/footer') %>
  out = out.replace(/<%- include\(['"]partials\/footer['"]\)\s*%>/g, () => footerRaw);
  return out;
};

const templateFiles = fs
  .readdirSync(dir)
  .filter((f) => f.endsWith(".ejs"))
  .sort();

const entries = templateFiles.map((f) => {
  const name = f.replace(/\.ejs$/, "");
  const content = inline(fs.readFileSync(path.join(dir, f), "utf-8"));
  return `  ${JSON.stringify(name)}: ${JSON.stringify(content)}`;
});

const output = `// AUTO-GENERATED by src/scripts/generateEmbeddedEmailTemplates.ts.
// Do not edit by hand - re-run the generator after changing .ejs templates.
export const EMBEDDED_TEMPLATES: Record<string, string> = {
${entries.join(",\n")}
};
`;

fs.writeFileSync(outPath, output, "utf-8");
console.log(`Wrote ${outPath} with ${templateFiles.length} templates (includes inlined).`);
